set windows-shell := ["pwsh", "-NoLogo", "-NoProfileLoadTime", "-Command"]

build:
  npx rspack --mode production -c ./rspack.config.cjs

dev *ARGS:
  npx rspack dev -c ./rspack.config.cjs {{ARGS}}

test: 
  node --import tsx --import "./test/loaders/loader.mjs" ./test/main.ts
